### ISSUE TITLE
Better Interface Support

### ISSUE THREAD

**Issue by amcdnl** [PLEEROCK/typedi#3]
It would be nice if one could do something like this:

```
import { Container } from 'typedi/Container';

import { IRecordRepository } from '../repository/IRecordRepository';
import { RecordRepository } from '../repository/neo4j/RecordRepository';

Container.provide([
  { name: 'RecordRepository', type: IRecordRepository, value: new RecordRepository() }
]);
```

then later do:

```
@Controller('/app/:appId/record')
export default class RecordController {
  
  @Inject()
  recRepository: IRecordRepository;

}
```

notice how I pointed it using interfaces vs a naming technique. Is this possible?

**Comment by PLEEROCK** [comment]
Decorators in typescript cannot extract information from the interface. Because interfaces are just "empty things" and used only by ts compiler and they are not getting compiled to js. Thats why its not possible for `@Inject` to get know the type of "recRepository" variable. Solution is to use [named services](https://github.com/PLEEROCK/typedi#named-services)

**Comment by amcdnl** [comment]
Gotcha. Thanks!
