### ISSUE TITLE
build with webpack 

### ISSUE THREAD

**Issue by korolariya** [pleerock/typedi#8]
> ritical dependency: the request of a dependency is an expression

**Comment by idchlife** [comment]
Error says for itself.

**Comment by pleerock** [comment]
he has this issue most probably because of experimental `@Require()` decorator. I think I'll remove this decorator in a near future and he wont have such problems with webpack anymore

**Comment by 19majkel94** [comment]
`@Require()` is great, works like a charm in node. The problem is that people doesn't understand how webpack/browserify works and what they do with `require()` functions. So you shouldn't remove it but place warning about browser environment.

I would even like to go futher and extend the decorator to provide an option to inject by require only part of the module which can imitate `import { foo } from "bar"` or `const { foo } = require("bar")` statements. It would help with mocking in testing when you only use one function/class of a module, like `fs` and `readFile`.

**Comment by pleerock** [comment]
> The problem is that people doesn't understand how webpack/browserify works

webpack/browserify automatically reads dynamic "require" and tries to replace them. Since we have such decorator it uses "require" and webpack breaks. Its a bad for user because he dont know whats going on.

The problem with `@Requre` that its not javascriptish way. I still think I'll remove this decorator. However typedi extendable system allows anyone to create its custom decorator, and its easy to create such `@Require` decorator as an extension.

**Comment by 19majkel94** [comment]
> However typedi extendable system allows anyone to create its custom decorator, and its easy to create such @Require decorator as an extension.

Yeah, it would be nice. You could remove it from the codebase but leave the note/sample about typedi extensions and how to implement own `@Require`.
The same thing would be with routing-controller - should `@JWT` be a part of framework like `@Session`? What about other decorators? If users should create it by themselves, what about DRY? Maybe we could have sth like a repository for custom extensions? List in docs with links to npm? What do you think @pleerock? :wink:

**Comment by pleerock** [comment]
I left @Require for now, but its still experimental, maybe will be removed in the future. Also I added docs on how to create a custom decorator in typedi.
